import { useState, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, Plus } from "lucide-react";
import { EmptyState, ErrorState, LoadingState } from "@/components/Feedback";
import { Button } from "@/components/ui/button";
import { getDashboard } from "@/features/dashboard/api/dashboard.api";
import { formatDate, formatDuration, formatThb, formatWeight, todayBangkok } from "@/lib/format";

function Card({ title, children, className = "" }: { title: string; children: ReactNode; className?: string }) {
  return <section className={`rounded-2xl border bg-card p-6 ${className}`}><h3 className="mb-5 text-sm font-semibold text-muted-foreground">{title}</h3>{children}</section>;
}

export function DashboardPage() {
  const [month, setMonth] = useState(() => todayBangkok().slice(0, 7));
  const query = useQuery({ queryKey: ["dashboard", month], queryFn: () => getDashboard(month), staleTime: 0, refetchOnMount: "always" });
  const data = query.data;
  const go = (path: string) => { window.location.hash = path; };
  const weights = data?.health.weight_trend ?? [];
  const values = weights.flatMap((point) => point.weight_kg === null ? [] : [Number(point.weight_kg)]);
  const low = values.length ? Math.min(...values) - 0.5 : 0;
  const high = values.length ? Math.max(...values) + 0.5 : 1;
  const x = (index: number) => 20 + index / Math.max(weights.length - 1, 1) * 560;
  const y = (value: string) => 130 - (Number(value) - low) / (high - low) * 110;
  const expenseMax = Math.max(1, ...(data?.finance.expense_by_category.map((row) => Number(row.amount)) ?? []));
  const cashMax = Math.max(1, Number(data?.finance.income ?? 0), Number(data?.finance.expense ?? 0));

  return <div className="grid gap-6">
    <div className="flex flex-wrap items-end justify-between gap-4">
      <label className="grid gap-2 text-sm font-medium">Reporting month<input className="rounded-lg border bg-card px-3 py-2" type="month" required value={month} onChange={(event) => { if (/^\d{4}-\d{2}$/.test(event.target.value)) setMonth(event.target.value); }} /></label>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => go("/finance?view=transactions")}><Plus />Transaction</Button><Button variant="outline" onClick={() => go("/health?view=weight")}><Plus />Weight</Button><Button variant="outline" onClick={() => go("/health?view=workouts")}><Plus />Workout</Button></div>
    </div>
    {query.isPending ? <LoadingState label="Loading your monthly snapshot…" /> : query.error ? <ErrorState message="Your dashboard could not be loaded. Check the connection and try again." onRetry={() => query.refetch()} /> : data && <>
      {query.isFetching && <p className="field-help" role="status">Refreshing snapshot…</p>}
      {!data.account_balances.items.length && <div className="rounded-xl border border-primary/30 bg-primary/5 p-5"><h3 className="font-semibold">Start with your first account</h3><p className="my-2 text-sm text-muted-foreground">Add a cash, bank, or e-wallet account to begin tracking your finances. You can also start with Health.</p><div className="flex gap-2"><Button onClick={() => go("/finance?view=accounts")}>Create account<ArrowUpRight /></Button><Button variant="ghost" onClick={() => go("/health?view=weight")}>Begin with Health</Button></div></div>}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <Card title="Total balance"><p className="text-3xl font-semibold tracking-tight text-primary">{formatThb(data.account_balances.total)}</p><p className="mt-2 text-xs text-muted-foreground">As of {formatDate(data.account_balances.as_of)} · includes archived accounts</p></Card>
        <Card title="Monthly income"><p className="text-3xl font-semibold tracking-tight">{formatThb(data.finance.income)}</p><p className="mt-2 text-xs text-muted-foreground">Transfers and opening balances excluded</p></Card>
        <Card title="Monthly expenses"><p className="text-3xl font-semibold tracking-tight">{formatThb(data.finance.expense)}</p><p className="mt-2 text-xs text-muted-foreground">Recorded expenses in {month}</p></Card>
        <Card title="Net cash flow"><p className="text-3xl font-semibold tracking-tight">{formatThb(data.finance.net_cash_flow)}</p><p className="mt-2 text-xs text-muted-foreground">Monthly income less expenses</p></Card>
      </div>
      <div className="grid gap-6 xl:grid-cols-2">
        <Card title="Expense by category">{data.finance.expense_by_category.length ? <ul className="grid gap-4">{data.finance.expense_by_category.map((row) => <li key={row.category_id}><div className="mb-2 flex justify-between gap-3 text-sm"><span>{row.category_name}</span><span>{formatThb(row.amount)}</span></div><div className="h-2 rounded bg-muted" aria-hidden="true"><div className="h-full rounded bg-primary" style={{ width: `${Number(row.amount) / expenseMax * 100}%` }} /></div></li>)}</ul> : <p className="text-sm text-muted-foreground">No expenses recorded this month.</p>}</Card>
        <Card title="Monthly cash flow"><div className="grid gap-5">{(["income", "expense"] as const).map((kind) => <div key={kind}><div className="mb-2 flex justify-between text-sm"><span className="capitalize">{kind}</span><span>{formatThb(data.finance[kind])}</span></div><div className="h-5 rounded bg-muted" aria-hidden="true"><div className={`h-full rounded ${kind === "income" ? "bg-primary" : "bg-destructive"}`} style={{ width: `${Number(data.finance[kind]) / cashMax * 100}%` }} /></div></div>)}</div></Card>
        <Card title="Monthly budgets">{data.budgets.length ? <ul className="grid gap-4">{data.budgets.map((budget) => <li key={budget.id} className="border-b pb-3 last:border-0"><div className="flex justify-between gap-2 text-sm"><span>{budget.category_name}</span><span>{formatThb(budget.actual)} / {formatThb(budget.amount)}</span></div><p className={`mt-1 text-xs ${Number(budget.remaining) < 0 ? "text-destructive" : "text-muted-foreground"}`}>{Number(budget.remaining) < 0 ? "Over budget" : "Remaining"}: {formatThb(Number(budget.remaining) < 0 ? budget.remaining.slice(1) : budget.remaining)}</p></li>)}</ul> : <><p className="mb-3 text-sm text-muted-foreground">No budgets set for this month.</p><Button variant="outline" onClick={() => go("/finance?view=budgets")}>Set a budget</Button></>}</Card>
        <Card title="Health at a glance"><div className="grid grid-cols-2 gap-5"><div><p className="text-2xl font-semibold">{data.health.latest_weight_kg === null ? "No weight yet" : formatWeight(data.health.latest_weight_kg)}</p><p className="mt-2 text-xs text-muted-foreground">{data.health.latest_weight_date ? `Latest: ${formatDate(data.health.latest_weight_date)}` : "Record your first weight in Health"}</p></div><div><p className="text-2xl font-semibold">{formatDuration(data.health.workout_minutes)}</p><p className="mt-2 text-xs text-muted-foreground">Workouts in {month}</p></div></div><p className="mt-5 text-sm text-muted-foreground">{data.health.average_weight_kg === null ? "No recorded weights this month." : `Monthly average ${formatWeight(data.health.average_weight_kg)} across ${data.health.recorded_weight_days} recorded days.`}</p></Card>
        <Card title="Weight this month" className="xl:col-span-2">{values.length ? <><svg className="h-44 w-full text-primary" viewBox="0 0 600 150" role="img" aria-label="Weight by date. Gaps indicate missing records."><title>Recorded weight trend for {month}</title><text x="0" y="12" fontSize="10" fill="currentColor">{high.toFixed(1)} kg</text><text x="0" y="147" fontSize="10" fill="currentColor">{low.toFixed(1)} kg</text>{weights.map((point, index) => point.weight_kg === null ? null : <g key={point.date}>{index > 0 && weights[index - 1].weight_kg !== null && <line x1={x(index - 1)} y1={y(weights[index - 1].weight_kg!)} x2={x(index)} y2={y(point.weight_kg)} stroke="currentColor" strokeWidth="2" />}<circle cx={x(index)} cy={y(point.weight_kg)} r="3.5" fill="currentColor"><title>{formatDate(point.date)}: {formatWeight(point.weight_kg)}</title></circle></g>)}</svg><div className="flex justify-between text-xs text-muted-foreground"><span>{weights[0]?.date}</span><span>{weights[weights.length - 1]?.date}</span></div><details className="mt-4 text-sm"><summary className="cursor-pointer">Recorded values · missing days remain gaps</summary><ul className="mt-3 flex flex-wrap gap-x-6 gap-y-2">{weights.filter((point) => point.weight_kg !== null).map((point) => <li key={point.date}>{formatDate(point.date)}: {formatWeight(point.weight_kg!)}</li>)}</ul></details></> : <p className="text-sm text-muted-foreground">No weight values recorded for this month. Missing records are never shown as zero.</p>}</Card>
        <Card title="Active goals">{data.goals.length ? <ul className="grid gap-4">{data.goals.map((goal) => <li key={goal.id}><div className="flex justify-between gap-2 text-sm"><span>{goal.name}</span><span>{goal.achieved ? "Achieved" : goal.progress_percent === null ? "Awaiting weight data" : `${Number(goal.progress_percent).toFixed(1)}%`}</span></div>{goal.progress_percent !== null && <progress className="mt-2 h-2 w-full accent-primary" max="100" value={Number(goal.progress_percent)} aria-label={`${goal.name} progress`} />}{goal.due_date && <p className="text-xs text-muted-foreground">Due {formatDate(goal.due_date)}</p>}</li>)}</ul> : <p className="text-sm text-muted-foreground">No active goals. Create an optional milestone in Goals.</p>}<Button className="mt-4" variant="ghost" onClick={() => go("/goals")}>View goals<ArrowUpRight /></Button></Card>
        <Card title="Accounts"><ul className="grid gap-3">{data.account_balances.items.map((account) => <li key={account.id} className="flex justify-between gap-3 text-sm"><span>{account.name}{account.archived_at ? " (archived)" : ""}</span><span>{formatThb(account.current_balance)}</span></li>)}</ul>{!data.account_balances.items.length && <p className="text-sm text-muted-foreground">Your accounts will appear here.</p>}</Card>
        <Card title="Five most recent transactions" className="xl:col-span-2">{data.recent_transactions.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-muted-foreground"><th className="pb-3">Date</th><th>Account</th><th>Type / category</th><th className="text-right">Amount</th></tr></thead><tbody>{data.recent_transactions.map((transaction) => <tr key={transaction.id} className="border-b last:border-0"><td className="py-3 pr-4 whitespace-nowrap">{formatDate(transaction.occurred_on)}</td><td className="pr-4">{transaction.account_name}{transaction.to_account_name ? ` → ${transaction.to_account_name}` : ""}</td><td className="pr-4">{transaction.category_name ?? "Transfer"}</td><td className="text-right whitespace-nowrap">{formatThb(transaction.amount)}</td></tr>)}</tbody></table></div> : <EmptyState title="No transactions yet" description="Record your first income or expense to see recent activity." action={<Button onClick={() => go("/finance?view=transactions")}>Record transaction</Button>} />}</Card>
      </div>
    </>}
  </div>;
}
